-- Check if API tables exist and have data
-- Run this script to verify database setup

-- Check if API_LICENSE table exists and has data
SELECT 'API_LICENSE Table Check' AS CHECK_TYPE, COUNT(*) AS RECORD_COUNT FROM API_LICENSE;

-- Show all licenses
SELECT 
    LICENSE_KEY,
    LICENSE_NAME,
    IS_ACTIVE,
    EXPIRY_DATE,
    MAX_REQUESTS_PER_DAY,
    TOTAL_REQUESTS,
    LAST_USED_DATE
FROM API_LICENSE
ORDER BY CREATED_DATE DESC;

-- Check if API_REQUEST_LOG table exists
SELECT 'API_REQUEST_LOG Table Check' AS CHECK_TYPE, COUNT(*) AS RECORD_COUNT FROM API_REQUEST_LOG;

-- Show recent API requests (last 10)
SELECT 
    LOG_ID,
    REQUEST_TIMESTAMP,
    REQUEST_METHOD,
    REQUEST_PATH,
    RESPONSE_STATUS,
    LICENSE_KEY,
    DURATION_MS
FROM API_REQUEST_LOG
ORDER BY REQUEST_TIMESTAMP DESC
FETCH FIRST 10 ROWS ONLY;
